"""Shared constants for engine modules."""

# Reasoning timeouts
REASONING_TIMEOUT_SECONDS = 3600
REASONING_INTENTS: frozenset[str] = frozenset({"complex", "code"})
REASONING_MODEL_ROLES: frozenset[str] = frozenset({"reasoning", "coding", "vision"})

# Summary chunking
SUMMARY_CHUNK_TRIGGER_CHARS = 6000
SUMMARY_CHUNK_MAX_CHARS = 3200
SUMMARY_CHUNK_OVERLAP_CHARS = 320

# Summary LLM calls
SUMMARY_MAP_TIMEOUT_SECONDS = 180
SUMMARY_REDUCE_TIMEOUT_SECONDS = 600
SUMMARY_MAP_MAX_TOKENS = 384
SUMMARY_REDUCE_MAX_TOKENS = 1024

# Full-scan analysis
FULL_SCAN_SEGMENT_MAX_CHARS = 12_000
FULL_SCAN_MAP_MAX_TOKENS = 384
FULL_SCAN_REDUCE_MAX_TOKENS = 768
FULL_SCAN_FINAL_MAX_TOKENS = 1600
FULL_SCAN_PROGRESS_EVERY_SEGMENTS = 10
FULL_SCAN_REDUCE_GROUP_MAX_CHARS = 12_000
FULL_SCAN_REDUCE_MAX_PASSES = 6

# Context history
CONTEXT_HISTORY_MESSAGE_MAX_CHARS = 32000
